[phases.setup]
nixPkgs = ["jdk17"]

[phases.build]
cmds = ["./mvnw clean package -DskipTests"]

[start]
cmd = "java -Xmx300m -Xms150m -Xss512k -XX:TieredStopAtLevel=1 -XX:+UseSerialGC -XX:CICompilerCount=2 -Dserver.port=$PORT -Djava.security.egd=file:/dev/./urandom -jar target/recruitsmart-crm-0.0.1-SNAPSHOT.jar"
