[phases.setup]
nixPkgs = ["jdk17"]

[phases.build]
cmds = ["./mvnw package -DskipTests"]

[start]
cmd = "java -Xmx256m -Dserver.port=$PORT -Djava.security.egd=file:/dev/./urandom -jar target/recruitsmart-crm-0.0.1-SNAPSHOT.jar"
